version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./backend/db.env
    ports:
      - "5555:5432" # host port 5555 -> container port 5432 (prevents conflict with local Postgres)
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
